### ISSUE TITLE
关于训练数据集的疑惑

### ISSUE THREAD

**Issue by GoPikachue** [wangzheyuan-666/FeNet#5]
作者你好！
    我看到你的工作中使用了DIV2K作为训练集，我想请问一下是只用了训练部分的800张图像还是所有的1000张图像呢？
    期待你的回复~

**Comment by wangzheyuan-666** [comment]
我们follow了之前的工作:仅仅使用训练集中的800张图像用于训练。

**Comment by GoPikachue** [comment]
好的，谢谢您的耐心答复~
